[package]
name = "football"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
rand = "0.7.0"
rayon = "1.2.0"
libm = "0.2.1"
rand_distr = "0.2.2"
