[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.0.0"
askama = "0.9.0"
lazy_static = "1.4.0"
core = { path = "src/core" }
actix-files = "0.3.0"
serde_json = "1.0.57"
serde = "1.0.116"
