[package]
name = "football"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
chrono = "0.4.7"
rand = "0.7.0"
rayon = "1.2.0"
libm = "0.2.1"
rand_distr = "0.2.2"
lazy_static = "1.4.0"
serde = "1.0.105"
serde_json = "1.0.48"
chashmap = "2.2.2"
actix-cors = "0.2.0"
env_logger = "0.7.1"