[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "src/core" }
actix-web = "3.3.2"
askama = "0.10.5"
lazy_static = "1.4.0"
actix-files = "0.5.0"
serde_json = "1.0.61"
serde = "1.0.120"
parking_lot = "0.11.1"
log = { version = "0.4.13", features = ["release_max_level_error"] }
env_logger = "0.8.2"
itertools = "0.10.0"
