[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
rand = "0.8.1"
rayon = "1.5.0"
rand_distr = "0.4.0"
serde = "1.0.118"
serde_json = "1.0.61"
log = { version = "0.4.11", features = ["release_max_level_debug"] }
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"