[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
rand = "0.8.3"
rayon = "1.5.0"
rand_distr = "0.4.0"
serde = "1.0.124"
serde_json = "1.0.64"
log = { version = "0.4.14", features = ["release_max_level_debug"] }
