[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
rand = "0.7.3"
rayon = "1.5.0"
rand_distr = "0.3.0"
lazy_static = "1.4.0"
serde = "1.0.117"
serde_json = "1.0.59"
log = { version = "0.4.11", features = ["release_max_level_off"] }
